### ISSUE TITLE
What is Host.io?

### ISSUE THREAD

**Issue by bartmichu** [dtex/j5e#93]
Hello. I'm trying to run some examples, but keep getting:

```
/home/XXX/XXX/XXX/moddable/j5e/lib/fn/index.js (157) # Exception: defaultProvider: get Host: undefined variable!
XS abort: unhandled rejection
```

I've tried with j5e installed via npm and with repo clone. I'm on latest release of Moddable SDK and I'm using ESP8266 board.
Any ideas, please?

**Comment by phoddie** [comment]
The TC53 specification [recommends](https://ecmatc53.github.io/spec/web/spec.html#-16-host-provider-instance-global-variable) the use of `device` for the global that provides access to the IO constructors. Before that recommendation was made, the implementation in the Moddable SDK used the global `Host`. The Moddable SDK has since been updated to use `device` as recommended by the draft standard.

A simple workaround for your scripts may be to alias `Host` to `device` at the top of the script:

```js
globalThis.Host = globalThis.device;
```

@dtex, if the above is correct, it looks like J5e needs to be updated to use replace uses of the `Host` global with `device`.

**Comment by bartmichu** [comment]
Thank you @phoddie I just tracked it down to [this change](https://github.com/Moddable-OpenSource/moddable/commit/1ae9eee571106ecdaf40dbc6fc275a4b27d44d4d) in Moddable. I can confirm that chaning ```Host.io``` to ```device.io``` fixes the problem for me.

**Comment by dtex** [comment]
@phoddie Thank you for confirming.

@bartmichu I'll get #94 landed tonight.
